name: Test

'on':
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9

    runs-on: ubuntu-${{ matrix.python-version == '3.7' && '22.04' || 'latest' }}

    steps:
      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Install Project
        run: |
          pip install -r requirements.txt
          pip install -e .

      - name: Test
        run: |
          nosetests
